#!/bin/bash
#
#   Cryptbaord - A X11 Encrypted Clipboard Manager
#
#   Depends: xdotool, xclip, GnuPG, pish
#   NOTE: http://github.com/tdwyer/pish
#
#   Cryptboard      GPLv3              v1.1
#   Thomas Dwyer    <devel@tomd.tel>   http://tomd.tel/
#
CONF="$HOME/.cryptboard.conf"
. ${CONF} 2>/dev/null
#
SELF="$(echo ${0} |rev |cut -d '/' -f 1 |rev)"
#
[[ -z ${CLIP_DEL_DEPTH} ]] && CLIP_DEL_DEPTH=10
XCLIP=$(which xclip 2>/dev/null)
XDO=$(which xdotool 2>/dev/null)
PINENTRY=$(which pish 2>/dev/null) # http://github.com/tdwyer/pish
GPG=$(which gpg 2>/dev/null)
#
GPGde="${GPG} -a --yes --batch"
#
GPGen="${GPG} -a -s -q --yes --batch"
[[ -z ${CIPHER} ]] && CIPHER="TWOFISH"
[[ -z ${DIGEST} ]] && DIGEST="SHA512"
GPGen+=" --cipher-algo ${CIPHER}"
GPGen+=" --digest-algo ${DIGEST}"
if [[ -z ${KEYID} ]] ;then
  GPGen+=" --default-recipient-self"
else
  GPGen+=" --recipient ${KEYID}"
fi
HELP="
Usage: ${SELF} [-i, --stdin] [ -a, --ask] [-c, --copy]
                  [-p, --paste] [-d, --delete]

${SELF} -i   :Read from stdin
${SELF} -a   :Ask with pinentry via ${PINENTRY}
${SELF} -c   :Encrypt primary to clipboard
${SELF} -p   :Decrypt clipboard to cursor position
${SELF} -d   :Delete all the things

echo 'encrypt to clipboard' | ${SELF} -i
Set these useful keyboard bindings in your DE or WM

Super+C = ${SELF} -c
Super+V = ${SELF} -p
Super+D = ${SELF} -d

Use normal Ctrl-V to paste the OpenPGP ASCII armor encrypted message

Configuration location: $HOME/.cryptboard.conf
KEYID=''  # Use default key as default recipient
CIPHER='' # Defualt TWOFISH-256
DIGEST='' # Default SHA512

${SELF} depends on GnuPG, xclip, xdotool, and pish
https://github.com/tdwyer/pish
"

case "${1}" in
  -i|--stdin)
    ${GPGen} -e | \
      ${XCLIP} -selection clipboard -i
    ;;
  -a|--ask)
    ${PINENTRY} | ${GPGen} -e | \
      ${XCLIP} -selection clipboard -i
    ;;
  -c|--copy)
    ${XCLIP} -selection primary -o | \
      ${GPGen} -e | \
      ${XCLIP} -selection clipboard -i
    echo -n '' | ${XCLIP} -selection primary -i
    ;;
  -p|--paste)
    sleep 0.5
    ${XDO} type "$(${XCLIP} -selection clipboard -o | ${GPGde} -d)"
    ;;
  -d|--delete)
    echo -n '' | ${XCLIP} -selection primary -i
    echo -n '' | ${XCLIP} -selection secondary -i
    # Other clipboard mangers on the system may buffer a history
    # Overflow their buffers do remove any sensitive data they may have
    while [[ ${i} -lt ${CLIP_DEL_DEPTH} ]] ;do
      echo -n '' | ${XCLIP} -selection clipboard -i
      i=$(expr ${i} + 1)
    done
    ;;
    *)
      echo "${HELP}"
esac

exit ${?}
