#!/bin/bash
#
#   Cryptbaord - A X11 Encrypted Clipboard Manager
#
#   Depends: xdotool, xclip, GnuPG, pish
#   NOTE: http://github.com/tdwyer/pish
#
#   cryptboard       GPLv3             v1.0
#   Thomas Dwyer    <devel@tomd.tel>   http://tomd.tel/
#


# Any Key ID gpg accepts for -r will work. alice@example.com, C18D3651, or fingerprint
KEYID="C18D3651"
DEL_DEPTH=10
PINENTRY=$(which pish) # The stinky one
GPG=$(which gpg) ;[[ ${?} -gt 0 ]] && (echo "Install gpg (GnuPG) >=2.0")
GPGen="${GPG} -a --batch --quiet --yes -s --cipher-algo TWOFISH --digest-algo SHA512"
GPGde="${GPG} -a --batch --quiet"
HELP="
Cryptboard depends on xclip, xdotool, and pish
http://github.com/tdwyer/pish

cryptboard -i   :Read from stdin
cryptboard -a   :Ask with pinentry via pish
cryptboard -c   :Encrypt primary to clipboard
cryptboard -p   :Decrypt clipboard to cursor position
cryptboard -d   :Delete all the things

echo 'Crypt to clipboard' | cryptboard -i
Set Keybindings in your DE, WM, or Gnu Screen. Something like this

Super-C = cryptboard -c
Super-V = cryptboard -p
Super-D = cryptboard -d

Use Ctrl-V to paste ASCII Armor GPG Encrypted Message
No more excuses. Encrypting and Decrypting GPG messages is stupid simple
"

case "${1}" in
  -i|--stdin)
    ${GPGen} -r "${KEYID}" -e | xclip -selection clipboard -i
    ;;
  -a|--ask)
    ${PINENTRY} | ${GPGen} -r "${KEYID}" -e | xclip -selection clipboard -i
    ;;
  -c|--copy)
    xclip -selection primary -o | ${GPGen} -r "${KEYID}" -e | xclip -selection clipboard -i
    echo -n '' | xclip -selection primary -i
    ;;
  -p|--paste)
    sleep 0.5
    xdotool type "$(xclip -selection clipboard -o | ${GPGde} -d)"
    ;;
  -d|--delete)
    echo -n '' | xclip -selection primary -i
    echo -n '' | xclip -selection secondary -i
    while [[ ${i} -lt ${DEL_DEPTH} ]] ;do
      echo -n '' | xclip -selection clipboard -i
      i=$(expr ${i} + 1)
    done
    ;;
    *)
      echo "${HELP}"
esac

exit 0
